apiVersion: v1  
kind: Service  
metadata:
  name: fwb-mgmt 
  labels:  
    app: fwb 
spec:  
  ports:  
  - name: http  
    port: 8008  
    targetPort: 8  
  selector:  
    app: fwb  
--- 
apiVersion: v1  
kind: Service  
metadata:
  name: fwb-traffic 
  labels:  
    app: fwb  
spec:  
  ports:  
  - name: http  
    port: 8080  
    targetPort: 80  
    protocol: TCP
  selector:  
    app: fwb  
--- 
apiVersion: extensions/v1beta1  
kind: Deployment  
metadata:  
  name: fwb  
spec:  
  replicas: 1  
  template:  
    metadata:  
      labels:  
        app: fwb  
        version: v1  
    spec:  
      containers:  
      - image: eu.gcr.io/ma-jx-gcp/fwb:6.2.0
        name: fwb  
         
